---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-credentials
  namespace: home-automation
spec:
  encryptedData:
    MQTT_PASSWORD: AgCS9DsARBec9m8jEEOKzkULgvRnKAllJheCHPJYOS67r4qRwYqAaJP0QdmI7XJRUbk4VeMI0YFG4a5okL9HOrL4HTFKU8j5GqV9zGlgzGlh+mWntlMjtWe3GK/LZU8uWSa2aSbOk4nE+omETbz0/an0trWDVVLyjJAptamTJLGCICX88tobsWc2VEimB9W6CxGgM++5SZXAZmo3BLFIib5mwfKE2tISdYdFZ9W5bqK0nnW4vj8Jp7eYXyh8p0nXZM/g5dZSLTO138SuBhaNhxtMgAUx/lKLQklO6721MtjVoPtknjDqskk5mRL7mDE9dpfXBED0+OEZLn4O3BeIBm7zZM4SxDDisfGclpoP1zJXpJvHP5hp/nd0mR0cZ/lS0vA0D1bjq1s+zlaBPYHmI2sZnkM6AX+GjmYY2SAIRt473vOnLyay/s8hXd3dHmf/WHC8yb1CROAn3EgRbnhySr/y/0QZ6oG+RD9HaYGi0o9rPB5subnAK97FPMIhKJWNM938ZW6LwZG9DHN781Sn891CpQj5KNJW19B1YljclkygkDReQVl/0lBmw/Swsgz/Y3Be463Q/sy7sSb+C8wcJyTqlX199w/wdrCYtZWhDmXl/fgnw0WEobRFaN8VgTIB2Myo5el1kEQtOit36sPzsV6ogPFCnEYATnqqQ701dSdrmStXBcb5cwf6kW8lJprgLaefB7Xs+sV/MsqNqVrLKgjJumSCenC+CcAfC5lnIj3uNVZOW2EKNStXOVyC
    MQTT_USER: AgCi6f6omNQ+No5AVwIBExZ8Hg766Hgr3d/BoYaN0eJbnRugxCkwWzrBVs8YV0XfkE6dAdy8rAADkK+Guqj4ce7NlMPRX4KKKbdyhiXOxKzQTW6NByxioI3cL8b8aUoyZXK/4aKpapw74DQ/Ei7nQraGM30IHY2ghfxNFBUcTk4iwHBllUbgXevtR87Ho1wGpQvQ/ixNllp3LhmQBz75lz7bBke4sk3RJe5MP9m/UOnG3WsTggolSeMRzdxxsqQN7lZqL+gv6w6+1twX4wy+DhLObBh7FiuaHGeAOEzvD4JAxdpuYlNk67WJ4IQ1gtRpxywjVOowiHjKH3OMt7LmfTOxmWvjCtcGF6zgkbBXlBvli/OMB6azFIzMtZxF2PlXXO8QAqeQyalLIybJ7YRpZOQQDpRq7RvXRo0TKbn9SwXdDmb/n7Alfkq9TjlPCNl55YbStNsppj1DAFNvTzeyt7BHt70IalDYmIzXACXNz8feXTm8Ftby3pmXQD6UUGISEz+Vm33EUaj1iurfD2BQxTMqV4b6UyKpRgJDMcdwnZnh1+KgmrnhLDrFpJ3mCkaZWV+wazZIEeA4AjxFs4X5PM/QQHZVOu/uFU5NhLO1cGWliihxnankvtT4jUIMtposwm+nDOs/pu4jF1myH3rK4FWdv6ijKvL/GXKqEMLmm2fSgOFvbUny+WMbG880aPfzQaAItLMl+zlS5WYBn9NaRg==
  template:
    metadata:
      name: mqtt-credentials
      namespace: home-automation
